openapi: 3.0.0

info:
  title: API Gestion Utilisateurs
  version: 1.0.0
  description: API pour lister des utilisateurs avec pagination.

paths:  
  /users:
    get:
      summary: Liste des utilisateurs avec pagination
      description: Retourne une liste d'utilisateurs paginée.
      parameters:
        - name: page.
          in: query
          description: Numéro de page.
          required: false
          schema:
            type: integer
          example: 1
        - name: size
          in: query
          description: Taille de la page.
          required: false
          schema:
            type: integer
          example: 20
      responses:
        '200':
          description: Liste des utilisateurs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
              example:
                - id: 1
                  name: Alice
                  email: alice@example.com
        '400':
          description: Mauvais paramètres.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Bad types for provided query parameters"